name: GitHub Actions Demo
run-name: ${{ github.actor }} is running backend tests 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./backend
      run: npm install 
    - name: Run tests
      working-directory: ./backend
      run: npm run test 