name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Enter Backend 
      run: cd ./backend 
    - name: Install modules
      run: npm install 
    - name: Run tests
      run: npm run test 